/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        
        // SearchAmazon search = new SearchAmazon();
        // search.SearchAmazon();
        // search.endTest();

        // Bookmyshow links = new Bookmyshow();
        // links.Bookmyshow();
        // links.endTest();

        LinkedinPost post = new LinkedinPost();
        post.LinkedinPost();
        post.endTest();
        
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
